<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();
$itemAmount       = $block->getItemAmount();
$selector         = 'alo-content-' . uniqid();
?>
<?php if (!is_countable($categories) || empty(count($categories))) return; ?>

<?php if ($heading): ?>
    <h3 class="magepow-categories-heading"><?php echo $heading ?></h3>
<?php endif; ?>
<div class="sub-categories mb-30 mb-lg-60 <?php echo $selector ?>" data-mage-init='{"gridSlider": {}}'>
    <div class="container">
    <ul class="grid-slider row magepow-categories-<?php echo $layout ?>" <?php foreach ($this->getFrontendCfg() as $opt) : ?> data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>' <?php endforeach; ?> <?php foreach ($this->getResponsiveBreakpoints() as $opt) : ?> data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>' <?php endforeach; ?>>
        <?php foreach ($categories as $cat): ?>
            <li class="category-item item">
                <div class="category-item-info">
                    <div class="category-image-container">
                        <a class="magepow-categories-category" href="<?php echo $cat->getUrl() ?>">
                            <div class="category-item-image mb-15 rounded-10 overflow-hidden d-flex">
                                <img loading="lazy" src="<?php echo $block->getImage($cat) ?>" alt="<?= $block->escapeHtml($cat->getName()) ?>"/>
                            </div>
                            <div class="category-item-name">
                                <span><?= $block->escapeHtml($cat->getName()) ?></span>
                            </div>
                        </a>
                    </div>
                    <?php if($description): ?>
                        <div class="category-item-description">
                            <?= $this->getDescription($cat) ?>
                        </div>
                    <?php endif; ?>
                    <?php if($itemAmount): ?>
                            <div class="category-item-amount">
                                    <?php echo "(".$cat->getProductCollection()->count();
                                        if($cat->getProductCollection()->count()>0)echo " items)";
                                        else echo " item)";
                                    ?>
                            </div>
                    <?php endif; ?>
                    <? /** 
                        <div class="btn-link">
                            <a href="<?php echo $cat->getUrl() ?>"><?= $block->escapeHtml(__('Show now')) ?></a>
                        </div>
                    */ ?>
                    
                </div>

            </li>
        <?php endforeach; ?>
    </ul>
    </div>
</div>
