<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:12
 */
?>
<?php
/**
 * Cmspage block
 *
 * @var $block \Magepow\Categories\Block\Cmspage
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();
?>
<?php if (empty($categories)) return ?>
<?php if ($heading): ?>
    <h3 class="magepow-categories-heading"><?php echo $heading ?></h3>
<?php endif; ?>
<ul class="magepow-categories-<?php echo $layout ?>">
    <?php foreach ($categories as $cat): ?>
        <li class="magepow-categories-category-wrapper">
            <a class="magepow-categories-category" href="<?php echo $cat->getUrl() ?>">
                <div class="magepow-categories-category-image">
                    <img src="<?php echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"/>
                </div>
                <div class="magepow-categories-category-name">
                    <span><?php echo $cat->getName() ?></span>
                </div>
            </a>
            <?php if($description): ?>
                <div class="magepow-categories-category-description">
                    <?php echo $this->getDescription($cat) ?>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>