<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:12
 */
?>
<?php
/**
 * Cmspage block
 *
 * @var $block \Magepow\Categories\Block\Cmspage
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();
$itemAmount       = $block->getItemAmount();
?>
<?php if (empty($categories)) return ?>
<?php if ($heading): ?>
    <h3 class="magepow-categories-heading"><?php echo $heading ?></h3>
<?php endif; ?>
<ul class="magepow-categories-<?php echo $layout ?>">
    <?php foreach ($categories as $cat): ?>
        <li class="magepow-categories-category-wrapper">
            <div class="magepow-categories-category-info">
                <div class="category-image-container">
                    <a class="magepow-categories-category" href="<?php echo $cat->getUrl() ?>">
                        <div class="magepow-categories-category-image">
                            <img loading="lazy" src="<?php  echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"/>
                        </div>
                        <div class="magepow-categories-category-name">
                            <span><?php echo $cat->getName() ?></span>
                        </div>
                    </a>
                </div>
                
                <?php if($description): ?>
                    <div class="magepow-categories-category-description">
                        <?php echo $this->getDescription($cat) ?>
                    </div>
                <?php endif; ?>
                <?php if($itemAmount): ?>
                        <div class="category-item-amount">
                                <?php echo "(".$cat->getProductCollection()->count();
                                    if($cat->getProductCollection()->count()>0)echo " items)";
                                    else echo " item)"; 
                                ?>
                        </div>
                <?php endif; ?>
                <div class="btn-link">
                    <a class="magepow-categories-category" href="<?php echo $cat->getUrl() ?>"><?= $block->escapeHtml(__('Show now')) ?></a>
                </div>               
            </div>
           
            
        </li>
    <?php endforeach; ?>
</ul>